[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

remappings = [
    "@agglayer/=lib/agglayer-contracts/contracts/"
]

# Emit extra output for test vector generation
ffi = false
verbosity = 2

# Allow writing test vectors to file
fs_permissions = [{ access = "read-write", path = "test-vectors" }]
