[package]
authors.workspace      = true
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "bench-transaction"
publish                = false
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[features]
concurrent = ["miden-tx/concurrent"]
default    = []

[[bench]]
harness = false
name    = "time_counting_benchmarks"
path    = "src/time_counting_benchmarks/prove.rs"

[dependencies]
# Workspace dependencies
miden-protocol  = { features = ["testing"], workspace = true }
miden-standards = { workspace = true }
miden-testing   = { workspace = true }
miden-tx        = { workspace = true }

# External dependencies
anyhow     = { workspace = true }
serde      = { features = ["derive"], version = "1.0" }
serde_json = { features = ["preserve_order"], package = "serde_json", version = "1.0" }
tokio      = { features = ["macros", "rt"], workspace = true }

[dev-dependencies]
criterion = { features = ["async_tokio", "html_reports"], version = "0.6" }
